@startuml
start
: 推送较简单的教程或是摘抄同业文章、炒作、广告等投送到微信、微博等其他公众平台，以此提升知名度； 经过五毛被诱导的众人和被减学费洗脑的学员以及HR推送公告到QQ群等其他社交群落;
: 赚够了钱就开设其他行业培训，即使名声臭了，但又借此在其他专业上培训又重新混名声，负面消息交钱给搜索优化的进行洗白或是以天朝法律威胁揭露者;

: xx开发实习生居多，通常的招聘条件很模糊，可以说是零门槛非专业生也能干的事，例如：
* 大专学历或不限，从事经验1年或不限，以及人数若干较多5-10人以上甚至不限
* 熟练使用计算机基本操作，喜欢计算机相关专业，且有强烈意愿在IT互联网上发展
* 工作认真、细致、敬业、责任心强、有较好学习能力者
* 包住（ 一般只有大厂业园区的公司才会这么做）;

:首先发一份面试通知，有的会主动直接确定5天的限期；当然有的培训机构没有确定明确的期限，只是短信上写诚邀应聘者届时面试;

if(是否面试) then (yes)

: 面试首先做个自我介绍、询问基本情况后、hr会向求职者简述公司大致情况；
然后，开始以diss的方式疯狂打击自信心（以非本科生或是没有经验为由等）以使其收取课程试听费或是贷款培训也就是智商税;

: 之后会有个面容姣好的女性讲师讲些简单的内容例如：html、css；hr时不时在上课期间的打断并催促面试者签下贷款协议；
正式开始上课前，让学员观看其培养的成功就业人士（演员）的采访视频，以及浮夸公司的“成就”，定期对学员“洗脑”教育拉人头减学费;

: 经包装过的二三流学院出来的“名师”照本宣科，重复某一章节模块课时讲解；项目课残缺不全敷衍了事，录制的内容跟占内存的垃圾一样;网上抄来过时的东西而做成的题库，实在没什么太多含金量可言;

else (no)
: 不管笔试过没过，hr都会诱使应聘者贷款培训，实在不行就会招个几乎完全免费的打杂苦工（低于当地省份市区最低薪资标准甚至没有薪水）；
如果笔试过了，就会以学历低下以及没经验的理由让诱使面试者培训（语气和善）
如果笔试没过，就会以说明利害（疯狂打击面试者的自信心）的方式，（所谓的包分配：他们给“安排”一个岗位用借口又给辞了，就是学员自己的事了）;

: 若是hr看到应聘者沮丧的样子，会以自然的神态让求职者签培训贷款协议成为其培训学员，
如果求职者打算要去别的公司，他还会“挽留”求职者说，过了这个村就没这店能成功应聘了;

: 如果应聘者入套就和面试入套之后的流程差不多了，仅仅只是大同小异而已;

stop


if(是否进行人才租赁（中介的形式）) then (yes)

: 任职的公司与中介签订人才租赁协议一次性付款给中介，工资由中介发放（这点培训机构可能稍有不同），
说白了就是为培训机构打工的临时工（贷款还欠着吸血公司的钱，出来工作又被培训机构抽了一笔血汗钱）;

else (no)

: 学历作假、经验作假套路多进与培训机构合作的一些杂七杂八的公司，例如：
小型房贷、催债、股票以及少数同类（培训）甚至自己旗下的皮包公司;

: 如被其推荐到上述公司而后不久又被开除，再去找它推荐工作，“老师”又是diss学员一顿，当然进入这种类型的公司对自身技能方面没什么发展可言的;

: 很多正经公司也并不是傻子，也会调查所辞的公司信息以及求职者人脉，当然被发现了也好不到哪去！;

stop

@enduml
